apiVersion: 1

datasources:
  - name: Tempo
    uid: nextstop-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: nextstop-loki
      serviceMap:
        datasourceUid: nextstop-prometheus
