import type {
  AiStatusSnapshot,
  DashboardHomeData,
  IntegrationRecord,
  LibraryPageData,
  MeetingArtifactRecord,
  MeetingExportRecord,
  MeetingFindingsRecord,
  OpsReadinessData,
  TranscriptAvailability,
  WebMeetingRecord,
  WorkspaceOverview,
} from "@/lib/workspace";

export const smokeGoogleReconnectRecord: IntegrationRecord = {
  user_id: "user-1",
  status: "reconnect_required",
  external_account_email: "krishna@example.com",
  metadata: {
    last_error: "Google session expired. Reconnect Google to continue.",
  },
};

export const smokeNotionNeedsDestinationRecord: IntegrationRecord = {
  user_id: "user-1",
  status: "needs_destination",
  external_workspace_name: "Krishna's Notion",
  selected_destination_id: null,
  selected_destination_name: null,
  metadata: {
    connected_via: "next_api",
    destination_type: null,
  },
};

export const smokeReadyMeeting: WebMeetingRecord = {
  id: "meeting-ready-1",
  user_id: "user-1",
  title: "Candidate Interview",
  source_type: "browser_tab",
  status: "ready",
  created_at: "2026-03-21T11:30:00.000Z",
};

export const smokeProcessingMeeting: WebMeetingRecord = {
  id: "meeting-processing-1",
  user_id: "user-1",
  title: "Product Review",
  source_type: "google_meet",
  status: "processing",
  created_at: "2026-03-21T12:00:00.000Z",
  session_metadata: {
    meet_url: "https://meet.google.com/example",
    event_url: "https://calendar.google.com/event?eid=abc",
    scheduled_start: "2026-03-21T13:00:00.000Z",
  },
};

export const smokeTranscriptReadyMeeting: WebMeetingRecord = {
  id: "meeting-transcript-ready-1",
  user_id: "user-1",
  title: "Design Review",
  source_type: "browser_tab",
  status: "transcript_ready",
  created_at: "2026-03-21T12:30:00.000Z",
};

export const smokeReadyFindings: MeetingFindingsRecord = {
  id: "findings-1",
  meeting_id: smokeReadyMeeting.id,
  user_id: "user-1",
  status: "ready",
  summary_short: "Strong alignment on backend ownership and API design.",
  summary_full:
    "The candidate demonstrated strong backend ownership, clear API design judgment, and comfort with production debugging.",
  executive_bullets_json: [
    "Strong backend ownership",
    "Comfortable with production debugging",
  ],
  decisions_json: ["Move the candidate to the final round."],
  action_items_json: ["Schedule the final technical round."],
  risks_json: ["Need deeper assessment on distributed systems depth."],
  follow_ups_json: ["Share the final-round prep notes with the panel."],
  email_draft: "Sharing the interview findings and next-step recommendation.",
  generation_mode: "openai_primary",
  generation_status: "full_success",
  fallback_reason: null,
  created_at: "2026-03-21T11:45:00.000Z",
};

export const smokeMeetingExports: MeetingExportRecord[] = [
  {
    id: "export-1",
    meeting_id: smokeReadyMeeting.id,
    user_id: "user-1",
    export_type: "pdf",
    status: "completed",
    created_at: "2026-03-21T11:50:00.000Z",
  },
  {
    id: "export-2",
    meeting_id: smokeReadyMeeting.id,
    user_id: "user-1",
    export_type: "notion",
    status: "completed",
    created_at: "2026-03-21T11:55:00.000Z",
  },
];

export const smokeMeetingArtifacts: MeetingArtifactRecord[] = [
  {
    id: "artifact-1",
    meeting_id: smokeReadyMeeting.id,
    user_id: "user-1",
    artifact_type: "summary",
    status: "ready",
    payload_text: smokeReadyFindings.summary_full,
    source_model: "gpt-4o-mini",
    version: 1,
  },
  {
    id: "artifact-2",
    meeting_id: smokeReadyMeeting.id,
    user_id: "user-1",
    artifact_type: "action_items",
    status: "ready",
    payload_text: smokeReadyFindings.action_items_json?.join("\n"),
    source_model: "gpt-4o-mini",
    version: 1,
  },
  {
    id: "artifact-3",
    meeting_id: smokeReadyMeeting.id,
    user_id: "user-1",
    artifact_type: "email_draft",
    status: "ready",
    payload_text: smokeReadyFindings.email_draft,
    source_model: "gpt-4o-mini",
    version: 1,
  },
];

export const smokeAiStatusReady: AiStatusSnapshot = {
  meetingId: smokeReadyMeeting.id,
  meetingStatus: "ready",
  latestJob: {
    id: "job-1",
    meeting_id: smokeReadyMeeting.id,
    user_id: "user-1",
    job_type: "transcribe",
    status: "ready",
    stage: "completed",
    provider_metadata: {
      transcription: {
        status: "ready",
        sourceModel: "deepgram:nova-2",
      },
      findings: {
        status: "ready",
        sourceModel: "gpt-4o-mini",
      },
    },
    created_at: "2026-03-21T11:46:00.000Z",
    updated_at: "2026-03-21T11:47:00.000Z",
  },
  artifacts: smokeMeetingArtifacts,
  transcriptAsset: null,
  rawAudioAsset: null,
  phase: "ready",
  transcriptReadyAt: "2026-03-21T11:46:30.000Z",
  findingsReadyAt: "2026-03-21T11:47:00.000Z",
  timings: {
    transcribeMs: 1200,
    analyzeMs: 950,
  },
  latestError: null,
  findingsGenerationMode: "openai_primary",
  findingsGenerationStatus: "full_success",
  findingsFallbackReason: null,
  surfaceState: "ready",
  pending: false,
};

export const smokeAiStatusProcessing: AiStatusSnapshot = {
  meetingId: smokeProcessingMeeting.id,
  meetingStatus: "analyzing",
  latestJob: {
    id: "job-2",
    meeting_id: smokeProcessingMeeting.id,
    user_id: "user-1",
    job_type: "transcribe",
    status: "running",
    stage: "normalizing",
    provider_metadata: {
      transcription: {
        status: "normalizing",
        sourceModel: "deepgram:nova-2",
      },
      findings: {
        status: "queued",
      },
    },
    created_at: "2026-03-21T12:01:00.000Z",
    updated_at: "2026-03-21T12:02:00.000Z",
  },
  artifacts: [],
  transcriptAsset: null,
  rawAudioAsset: null,
  phase: "transcribing",
  transcriptReadyAt: null,
  findingsReadyAt: null,
  timings: null,
  latestError: null,
  findingsGenerationMode: null,
  findingsGenerationStatus: null,
  findingsFallbackReason: null,
  surfaceState: "processing",
  pending: true,
  cancelable: true,
  temporaryTranscriptReady: false,
};

export const smokeAiStatusTranscriptReady: AiStatusSnapshot = {
  meetingId: smokeTranscriptReadyMeeting.id,
  meetingStatus: "transcript_ready",
  latestJob: {
    id: "job-4",
    meeting_id: smokeTranscriptReadyMeeting.id,
    user_id: "user-1",
    job_type: "analyze",
    status: "running",
    stage: "extracting",
    provider_metadata: {
      transcription: {
        status: "ready",
        sourceModel: "deepgram:nova-2",
      },
      findings: {
        status: "running",
      },
    },
    created_at: "2026-03-21T12:32:00.000Z",
    updated_at: "2026-03-21T12:33:00.000Z",
  },
  artifacts: [],
  transcriptAsset: null,
  rawAudioAsset: null,
  phase: "transcribing",
  transcriptReadyAt: "2026-03-21T12:32:30.000Z",
  findingsReadyAt: null,
  timings: {
    transcribeMs: 1400,
  },
  latestError: null,
  findingsGenerationMode: null,
  findingsGenerationStatus: null,
  findingsFallbackReason: null,
  surfaceState: "processing",
  pending: true,
  captureStatus: "queued_for_transcription",
  cancelable: true,
  temporaryTranscriptReady: true,
};

export const smokeTranscriptDisabled: TranscriptAvailability = {
  status: "disabled",
  downloadEnabled: false,
  message: "Transcript downloads are disabled for this production launch. Findings remain available.",
  expiresAt: null,
};

export const smokeTranscriptAvailable: TranscriptAvailability = {
  status: "available",
  downloadEnabled: true,
  message: "Transcript downloads remain available for a short retention window.",
  expiresAt: "2026-03-21T15:00:00.000Z",
};

export const smokeTranscriptNotReady: TranscriptAvailability = {
  status: "not_ready",
  downloadEnabled: false,
  message: "Transcript is still processing and will be available shortly.",
  expiresAt: null,
};

export const smokeDegradedMeeting: WebMeetingRecord = {
  id: "meeting-degraded-1",
  user_id: "user-1",
  title: "Go To Market Sync",
  source_type: "google_meet",
  status: "partial_success",
  created_at: "2026-03-21T14:00:00.000Z",
};

export const smokeDegradedFindings: MeetingFindingsRecord = {
  id: "findings-degraded-1",
  meeting_id: smokeDegradedMeeting.id,
  user_id: "user-1",
  status: "ready",
  summary_short: "Fallback findings were generated after the primary model path failed.",
  summary_full:
    "The transcript was available, but structured findings were assembled via the local fallback path after the OpenAI request failed.",
  executive_bullets_json: ["Primary model path failed", "Fallback findings are still reviewable"],
  decisions_json: ["Review before external sharing."],
  action_items_json: ["Retry extraction when the AI worker is healthy."],
  risks_json: ["Some nuance may be missing from fallback extraction."],
  follow_ups_json: ["Monitor worker health and re-run extraction."],
  email_draft: "Sharing the fallback findings with a note to review them manually.",
  generation_mode: "fallback_local",
  generation_status: "degraded_success",
  fallback_reason: "openai request timed out",
  created_at: "2026-03-21T14:12:00.000Z",
};

export const smokeAiStatusDegraded: AiStatusSnapshot = {
  meetingId: smokeDegradedMeeting.id,
  meetingStatus: "partial_success",
  latestJob: {
    id: "job-3",
    meeting_id: smokeDegradedMeeting.id,
    user_id: "user-1",
    job_type: "analyze",
    status: "partial_success",
    stage: "completed",
    provider_metadata: {
      transcription: {
        status: "ready",
        sourceModel: "deepgram:nova-2",
      },
      findings: {
        status: "degraded_success",
        sourceModel: "fallback-local",
      },
    },
    created_at: "2026-03-21T14:08:00.000Z",
    updated_at: "2026-03-21T14:12:00.000Z",
  },
  artifacts: [],
  transcriptAsset: null,
  rawAudioAsset: null,
  phase: "ready",
  transcriptReadyAt: "2026-03-21T14:09:00.000Z",
  findingsReadyAt: "2026-03-21T14:12:00.000Z",
  timings: {
    transcribeMs: 1300,
    analyzeMs: 2100,
  },
  latestError: null,
  findingsGenerationMode: "fallback_local",
  findingsGenerationStatus: "degraded_success",
  findingsFallbackReason: "openai request timed out",
  surfaceState: "degraded",
  pending: false,
};

export const smokeWorkspaceOverview: WorkspaceOverview = {
  google: smokeGoogleReconnectRecord,
  notion: smokeNotionNeedsDestinationRecord,
  meetings: [
    {
      ...smokeProcessingMeeting,
      status: "processing",
    },
    smokeDegradedMeeting,
    smokeReadyMeeting,
  ],
  latestAiJob: smokeAiStatusProcessing.latestJob,
  findingsByMeetingId: {
    [smokeReadyMeeting.id]: smokeReadyFindings,
    [smokeDegradedMeeting.id]: smokeDegradedFindings,
  },
  exportsByMeetingId: {
    [smokeReadyMeeting.id]: smokeMeetingExports,
  },
  aiStatusByMeetingId: {
    [smokeReadyMeeting.id]: smokeAiStatusReady,
    [smokeProcessingMeeting.id]: smokeAiStatusProcessing,
    [smokeDegradedMeeting.id]: smokeAiStatusDegraded,
    [smokeTranscriptReadyMeeting.id]: smokeAiStatusTranscriptReady,
  },
  providerStatus: {
    deepgramConfigured: true,
    openAiConfigured: true,
    aiCoreConfigured: true,
    huggingFaceConfigured: true,
    googleConfigured: true,
    googleRefreshConfigured: false,
    notionConfigured: true,
    transcriptDownloadsEnabled: false,
    transcriptStorageMode: "disabled",
    transcriptRetentionMinutes: 60,
    rawAssetRetentionHours: 24,
    aiPipelineMode: "railway_remote",
  },
};

export const smokeOpsReadinessData: OpsReadinessData = {
  checks: [
    {
      name: "Frontend app URL",
      status: "pass",
      detail: "https://app.nextstop.ai",
    },
    {
      name: "AI core direct execution",
      status: "warn",
      detail: "Railway worker is ready, but one recent meeting completed in degraded mode.",
    },
    {
      name: "Retention cleanup",
      status: "warn",
      detail: "Cleanup is running, but there are still expired assets pending deletion.",
    },
  ],
  blockingFailures: [],
  warnings: [
    {
      name: "AI degraded mode",
      detail: "Fallback findings were generated for one recent meeting.",
    },
    {
      name: "Retention cleanup",
      detail: "Cleanup is healthy but still has pending expired assets to delete.",
    },
  ],
  launchDecision: "degraded",
  aiCoreHealth: {
    ok: true,
    queue: "nextstop-ai-jobs",
    workerReady: true,
    directExecution: false,
  },
  recentAiFailures: [
    {
      id: "job-fail-1",
      meetingId: "meeting-ready-1",
      jobType: "transcribe",
      stage: "transcribing",
      status: "failed",
      error: "Deepgram returned an empty transcript.",
      executionMode: "railway_remote",
      findingsGenerationStatus: "failed",
      createdAt: "2026-03-21T12:10:00.000Z",
    },
  ],
  recentDegradedMeetings: [
    {
      meetingId: smokeDegradedMeeting.id,
      title: smokeDegradedMeeting.title,
      generationMode: "fallback_local",
      generationStatus: "degraded_success",
      fallbackReason: "openai request timed out",
      updatedAt: "2026-03-21T14:12:00.000Z",
    },
  ],
  recentExportFailures: [
    {
      id: "export-fail-1",
      meetingId: "meeting-ready-1",
      exportType: "pdf",
      status: "failed",
      destination: "browser download",
      latestError: "PDF generation timed out.",
      durationMs: 1842,
      createdAt: "2026-03-21T12:12:00.000Z",
    },
  ],
  appUrl: "https://app.nextstop.ai",
  backendApiUrl: "https://nextstopai-web-backend-production.up.railway.app",
  aiCoreApiUrl: "https://nextstopai-web-backend-production.up.railway.app",
  workerReady: true,
  queueName: "nextstop-ai-jobs",
  lastWorkerHeartbeatAt: "2026-03-21T12:09:00.000Z",
  workerVersion: "2026.04.18-hardening",
  cleanup: {
    lastCleanupRunAt: "2026-03-21T12:15:00.000Z",
    lastCleanupSuccessAt: "2026-03-21T12:15:00.000Z",
    lastCleanupError: null,
    deletedAudioAssetCount: 6,
    deletedTranscriptAssetCount: 4,
    pendingExpiredAssetCount: 2,
  },
  security: {
    lastEventAt: "2026-03-21T12:16:00.000Z",
    lastRateLimitDeniedAt: "2026-03-21T12:16:00.000Z",
    lastTranscriptDownloadGrantedAt: "2026-03-21T12:14:00.000Z",
    lastTranscriptDownloadBlockedAt: "2026-03-21T12:15:00.000Z",
    lastExportRequestedAt: "2026-03-21T12:13:00.000Z",
    rateLimitDeniedCount: 3,
    transcriptDownloadGrantedCount: 5,
    transcriptDownloadBlockedCount: 2,
    exportRequestedCount: 7,
    denialByPolicy: {
      transcript_download: 2,
      pdf_export: 1,
    },
    transcriptBlocksByReason: {
      expired: 1,
      deleted: 1,
    },
    exportRequestsByPolicy: {
      pdf_export: 4,
      notion_export: 3,
    },
  },
  hostedVerification: {
    lastHostedVerificationAt: "2026-03-21T12:20:00.000Z",
    lastHostedVerificationStatus: "partial",
    lastHostedVerificationScenario: "browser_close_after_end",
    lastHostedVerificationFailureReason:
      "Manual durable-flow scenarios are partially complete; deployment smoke is green.",
    source: "workflow",
    scenarios: {
      readiness_api: {
        status: "pass",
        detail: "Readiness endpoint returned a launch decision and healthy checks.",
        checkedAt: "2026-03-21T12:17:00.000Z",
      },
      backend_health: {
        status: "pass",
        detail: "Worker heartbeat and cleanup health were healthy.",
        checkedAt: "2026-03-21T12:17:30.000Z",
      },
      browser_close_after_end: {
        status: "partial",
        detail: "Manual verification is still required after the next production deploy.",
        checkedAt: "2026-03-21T12:20:00.000Z",
      },
    },
  },
  launchCertification: {
    lastLaunchCertificationAt: "2026-03-21T12:21:00.000Z",
    lastLaunchCertificationStatus: "pending",
    certifiedBy: "engineering@nextstop.ai",
    certificationNotes: "Waiting for full durable-flow hosted verification before broad-green launch.",
    validationGreen: true,
    hostedVerificationPassed: false,
    operationalProofComplete: false,
    readinessLaunchDecision: "degraded",
  },
  captureRuntime: {
    activeCaptureSessionCount: 2,
    staleCaptureSessionCount: 0,
    finalizationBacklogCount: 1,
    transcriptReadyAwaitingAnalysisCount: 1,
    cancelRequestedJobCount: 1,
    sessions: [
      {
        captureSessionId: "capture-1",
        meetingId: smokeTranscriptReadyMeeting.id,
        meetingTitle: smokeTranscriptReadyMeeting.title,
        status: "queued_for_transcription",
        lastHeartbeatAt: "2026-03-21T12:31:00.000Z",
        lastChunkReceivedAt: "2026-03-21T12:30:45.000Z",
        totalChunksReceived: 24,
        totalBytesReceived: 1840000,
        error: null,
      },
      {
        captureSessionId: "capture-2",
        meetingId: smokeProcessingMeeting.id,
        meetingTitle: smokeProcessingMeeting.title,
        status: "materializing_audio",
        lastHeartbeatAt: "2026-03-21T12:02:00.000Z",
        lastChunkReceivedAt: "2026-03-21T12:01:40.000Z",
        totalChunksReceived: 12,
        totalBytesReceived: 920000,
        error: null,
      },
    ],
  },
  lastDeployHint: "Use the post-deploy verification workflow summary to confirm the latest Vercel and Railway release.",
  observabilityLinks: {
    grafanaOverviewUrl: "https://grafana.example.com/d/overview",
    grafanaLogsUrl: "https://grafana.example.com/explore?logs=1",
    grafanaTracesUrl: "https://grafana.example.com/explore?traces=1",
    sentryIssuesUrl: "https://sentry.example.com/issues/",
    syntheticMonitoringUrl:
      "https://grafana.example.com/a/grafana-synthetic-monitoring-app/checks",
  },
};

export const smokeDashboardHomeData: DashboardHomeData = {
  google: smokeGoogleReconnectRecord,
  notion: smokeNotionNeedsDestinationRecord,
  latestAiJob: smokeAiStatusProcessing.latestJob,
  aiQueueStatus: {
    queuedCount: 1,
    runningCount: 1,
    failedCount: 0,
    cancelRequestedCount: 0,
  },
  providerStatus: smokeWorkspaceOverview.providerStatus,
};

export const smokeLibraryPageData: LibraryPageData = {
  query: "",
  limit: 20,
  nextCursor: "cursor-next-page",
  providerStatus: smokeWorkspaceOverview.providerStatus,
  cards: [
    {
      id: smokeProcessingMeeting.id,
      title: smokeProcessingMeeting.title,
      status: "processing",
      sourceType: smokeProcessingMeeting.source_type,
      originPlatform: smokeProcessingMeeting.origin_platform ?? "web",
      googleEventId: smokeProcessingMeeting.google_event_id ?? null,
      createdAt: smokeProcessingMeeting.created_at ?? null,
      endedAt: smokeProcessingMeeting.ended_at ?? null,
      scheduledStart: "2026-03-21T13:00:00.000Z",
      summaryShort: null,
      latestAiStage: "normalizing",
      latestError: null,
      phase: "transcribing",
      exportCount: 0,
      artifactCount: 0,
      transcriptExpiresAt: null,
      findingsGenerationMode: null,
      findingsGenerationStatus: null,
      findingsFallbackReason: null,
      reviewState: "processing",
      meetUrl: "https://meet.google.com/example",
      eventUrl: "https://calendar.google.com/event?eid=abc",
    },
    {
      id: smokeTranscriptReadyMeeting.id,
      title: smokeTranscriptReadyMeeting.title,
      status: "transcript_ready",
      sourceType: smokeTranscriptReadyMeeting.source_type,
      originPlatform: smokeTranscriptReadyMeeting.origin_platform ?? "web",
      googleEventId: smokeTranscriptReadyMeeting.google_event_id ?? null,
      createdAt: smokeTranscriptReadyMeeting.created_at ?? null,
      endedAt: smokeTranscriptReadyMeeting.ended_at ?? null,
      scheduledStart: null,
      summaryShort: null,
      latestAiStage: "extracting",
      latestAiJobStatus: "running",
      latestError: null,
      phase: "transcribing",
      captureStatus: "queued_for_transcription",
      cancelable: true,
      temporaryTranscriptReady: true,
      exportCount: 0,
      artifactCount: 0,
      transcriptExpiresAt: "2026-03-21T15:30:00.000Z",
      findingsGenerationMode: null,
      findingsGenerationStatus: null,
      findingsFallbackReason: null,
      reviewState: "processing",
      meetUrl: null,
      eventUrl: null,
    },
    {
      id: smokeDegradedMeeting.id,
      title: smokeDegradedMeeting.title,
      status: "partial_success",
      sourceType: smokeDegradedMeeting.source_type,
      originPlatform: smokeDegradedMeeting.origin_platform ?? "web",
      googleEventId: smokeDegradedMeeting.google_event_id ?? null,
      createdAt: smokeDegradedMeeting.created_at ?? null,
      endedAt: smokeDegradedMeeting.ended_at ?? null,
      scheduledStart: null,
      summaryShort: smokeDegradedFindings.summary_short ?? null,
      latestAiStage: "completed",
      latestError: null,
      phase: "ready",
      exportCount: 0,
      artifactCount: 0,
      transcriptExpiresAt: "2026-03-21T15:00:00.000Z",
      findingsGenerationMode: "fallback_local",
      findingsGenerationStatus: "degraded_success",
      findingsFallbackReason: "openai request timed out",
      reviewState: "degraded",
      meetUrl: null,
      eventUrl: null,
    },
    {
      id: smokeReadyMeeting.id,
      title: smokeReadyMeeting.title,
      status: "ready",
      sourceType: smokeReadyMeeting.source_type,
      originPlatform: smokeReadyMeeting.origin_platform ?? "web",
      googleEventId: smokeReadyMeeting.google_event_id ?? null,
      createdAt: smokeReadyMeeting.created_at ?? null,
      endedAt: smokeReadyMeeting.ended_at ?? null,
      scheduledStart: null,
      summaryShort: smokeReadyFindings.summary_short ?? null,
      latestAiStage: "completed",
      latestError: null,
      phase: "ready",
      exportCount: smokeMeetingExports.length,
      artifactCount: smokeMeetingArtifacts.length,
      transcriptExpiresAt: null,
      findingsGenerationMode: "openai_primary",
      findingsGenerationStatus: "full_success",
      findingsFallbackReason: null,
      reviewState: "ready",
      meetUrl: null,
      eventUrl: null,
    },
  ],
};
